import RecentQualityRuns from './RecentQualityRuns'
import QualityRules from '../../app/components/QualityRules'
import {Badge,Button,Card,DataTable,EmptyState,ErrorState,LoadingState,SectionHeader,ruleLabel} from '../ui'
import {QualityMetrics} from '../datasets/ProfilePanels'
import type {Profile,Quality,RunState} from '../datasets/types'
export default function QualityPanel({quality,profile,state,run,runProfile,sourceId,schema,table,onRulesChanged,historyRevision}:{quality:Quality|null;profile:Profile|null;state:RunState;run:()=>void;runProfile:()=>void;sourceId:string;schema:string;table:string;onRulesChanged:()=>void;historyRevision:number}){
 return <div className="stack">{state==='running'&&<LoadingState>Running quality checks...</LoadingState>}{state==='error'&&<ErrorState retry={run}>We couldn’t run quality checks. Check the source connection and try again.</ErrorState>}{quality?<section aria-label="Current Result"><SectionHeader title="Current Result" description="The most recent quality result executed in this session."/><QualityMetrics quality={quality}/></section>:state!=='running'&&<Card><EmptyState title="No quality result available yet" description="Run quality checks to evaluate this dataset with automatic and configured rules." action={<Button onClick={run}>Run Quality Checks</Button>}/></Card>}
 {profile?<QualityRules sourceId={sourceId} schema={schema} table={table} columns={profile.columns} onChanged={onRulesChanged}/>:<Card><SectionHeader title="Quality Rules"/><EmptyState title="Profile this dataset to configure rules" description="Column metadata determines which rules are compatible. Automatic metadata checks still run without configured rules." action={<Button variant="secondary" onClick={runProfile}>Run Profile</Button>}/></Card>}
 {quality&&<Card><SectionHeader title="Checks / Issues" description={`${quality.summary.checks} checks evaluated`} action={<div className="check-summary"><Badge tone="passed">{quality.summary.passed} passed</Badge><Badge tone="warning">{quality.summary.warnings} warnings</Badge><Badge tone="failed">{quality.summary.failed} failed</Badge></div>}/><DataTable label="Quality checks"><thead><tr><th>Check</th><th>Column</th><th>Score</th><th>Affected</th><th>Status</th></tr></thead><tbody>{quality.checks.map((c,i)=><tr key={i}><td><div className="cell-title">{ruleLabel(c.rule)}</div>{c.message&&<p className="muted text-xs mt-1 max-w-sm">{c.message}</p>}</td><td className="cell-mono">{c.columns?.join(', ')||c.column||'—'}</td><td>{c.score.toFixed(2)}</td><td>{c.failed_count} <span className="muted">· {c.failed_percentage.toFixed(2)}%</span></td><td><Badge tone={c.status}>{c.status}</Badge></td></tr>)}</tbody></DataTable></Card>}<RecentQualityRuns sourceId={sourceId} schema={schema} table={table} revision={historyRevision}/></div>
}
