const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,dependencies={},globals={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,require:n=>dependencies[n]||require(n),...globals});return module.exports}
const h=load('components/quality/history.ts');
function run(id,score,validity=score){return {id,source_id:1,schema:'public',table:'customers',overall_score:score,completeness_score:score,uniqueness_score:100,validity_score:validity,created_at:new Date(1700000000000+id*1000).toISOString()}}
test('deltas use score points, sign, zero and N/A',()=>{for(const [a,b,want] of [[99.11,98.11,'+1.00'],[98.11,99.11,'-1.00'],[100,100,'0.00'],[null,100,'N/A'],[100,null,'N/A']])assert.equal(h.formatDelta(h.delta(a,b)),want)});
for(const count of [0,1,2,20])test(`${count} runs preserve newest-first history and chronological chart ordering`,()=>{const rows=Array.from({length:count},(_,i)=>run(count-i,90+i));const before=JSON.stringify(rows),ordered=h.chronological(rows);assert.equal(JSON.stringify(rows),before);assert.equal(ordered.length,count);if(count)assert.equal(ordered[0].id,1);const c=h.comparison(rows,'overall_score');assert.equal(c.latest,count?90:null);assert.equal(c.previous,count>1?91:null)});
test('latest 92 vs previous 95 returns -3 with older 90',()=>{const c=h.comparison([run(3,92),run(2,95),run(1,90)],'overall_score');assert.equal(c.latest,92);assert.equal(c.previous,95);assert.equal(c.change,-3)});
test('nullable dimensions remain gaps and are not compared to zero',()=>{const rows=[run(3,92,null),run(2,95,90),run(1,90,null)];assert.equal(h.comparison(rows,'validity_score').change,null);assert.equal(h.chronological(rows)[0].validity_score,null);assert.equal(h.formatScore(null),'N/A')});
test('chart uses one linear series, fixed scale, chronology and gaps',()=>{const names=['CartesianGrid','Line','LineChart','ResponsiveContainer','Tooltip','XAxis','YAxis'];const charts=Object.fromEntries(names.map(n=>[n,n]));const Chart=load('components/quality/QualityTrendChart.tsx',{'recharts':charts,'./history':h,'../ui':{EmptyState:'EmptyState'}}).default;const rows=[run(3,92),run(2,95,null),run(1,90)];const tree=Chart({runs:rows,metric:'validity_score'});function find(el,type){if(!el)return [];if(Array.isArray(el))return el.flatMap(x=>find(x,type));return [...(el.type===type?[el]:[]),...find(el.props?.children,type)]}const line=find(tree,'Line');assert.equal(line.length,1);assert.equal(line[0].props.connectNulls,false);assert.equal(line[0].props.dataKey,'validity_score');assert.equal(JSON.stringify(find(tree,'YAxis')[0].props.domain),'[0,100]');assert.equal(find(tree,'LineChart')[0].props.data[0].id,1);assert.equal(find(tree,'LineChart')[0].props.data[1].validity_score,null);assert.equal(find(tree,'Tooltip').length,1)});

test('history filters request limits and revision refresh exposes the new run',async()=>{
  const states=[],effects=[],requests=[];let cursor=0,refCursor=0,rows=[run(2,95),run(1,90)];const refs=[];
  const mockReact={useState:initial=>{const i=cursor++;if(!(i in states))states[i]=initial;return [states[i],value=>{states[i]=typeof value==='function'?value(states[i]):value}]},useRef:()=>{const i=refCursor++;return refs[i]||(refs[i]={current:null})},useEffect:(callback,deps)=>effects.push({callback,deps})};
  const ui=Object.fromEntries(['Badge','Button','Card','DataTable','EmptyState','ErrorState','LoadingState','MetricCard','SectionHeader'].map(n=>[n,n]));ui.ruleLabel=x=>x;
  const C=load('components/quality/RecentQualityRuns.tsx',{'react':mockReact,'../ui':ui,'../datasets/ProfilePanels':{QualityMetrics:'QualityMetrics'},'./QualityTrendChart':{default:'QualityTrendChart'},'./history':h},{URLSearchParams,AbortController,fetch:async(url)=>{requests.push(url);return {ok:true,json:async()=>rows}}}).default;
  function render(revision){cursor=0;refCursor=0;return C({sourceId:'1',schema:'public',table:'customers',revision})}
  async function executeEffect(){effects.at(-1).callback();await new Promise(resolve=>setImmediate(resolve));assert.equal(states[1],'success')}
  function find(el,type){if(!el)return null;if(Array.isArray(el)){for(const child of el){const r=find(child,type);if(r)return r}return null}if(el.type===type)return el;return find(el.props?.children,type)||find(el.props?.action,type)}
  render(0);await executeEffect();assert.match(requests.at(-1),/limit=20/);assert.equal(states[0][0].id,2);
  for(const limit of [10,20,50]){find(render(0),'select').props.onChange({target:{value:String(limit)}});assert.equal(states[1],'loading');assert.equal(states[0].length,0);render(0);await executeEffect();assert.match(requests.at(-1),new RegExp('limit='+limit))}
  rows=[run(3,92),...rows];render(1);assert.equal(effects.at(-1).deps[3],1);await executeEffect();assert.equal(states[0][0].id,3);
  const tree=render(1),chart=find(tree,'QualityTrendChart');assert.equal(chart.props.runs[0].overall_score,92);assert.equal(h.comparison(chart.props.runs,'overall_score').change,-3);
});
