import {Badge,Button,Card,EmptyState,ErrorState,LoadingState,SectionHeader,ruleLabel} from '../ui'
import type {Insights} from '../datasets/types'
export default function InsightsPanel({available,state,insights,run}:{available:boolean|null;state:string;insights:Insights|null;run:()=>void}){
 return <Card><SectionHeader title="AI Insights" description="Optional analysis of profiling and quality results. Recommendations do not change checks or scores."/>
 {(available===false||state==='unavailable')?<EmptyState title="AI Insights are optional and currently not configured." description="Profiling and deterministic quality checks remain fully available."/>:available===null?<LoadingState>Checking AI availability...</LoadingState>:<>
 {state==='idle'&&<EmptyState title="Interpret your dataset" description="Use AI to interpret profiling and quality results." action={<Button onClick={run}>Generate AI Insights</Button>}/>}{state==='running'&&<LoadingState>Generating insights...</LoadingState>}{state==='error'&&<ErrorState retry={run}>AI insights could not be generated. Profiling and Quality remain available.</ErrorState>}
 {state==='success'&&insights&&<><div className="section-header"><div><p className="metric-label mb-2">Risk Level</p><Badge tone={insights.risk_level}>{insights.risk_level.toUpperCase()}</Badge></div><Button variant="secondary" onClick={run}>Generate again</Button></div><div className="inline-panel"><h3>Summary</h3><p className="mt-2">{insights.summary}</p></div><h2 className="mt-7">Key Findings</h2>{!insights.findings.length&&<p className="muted mt-2">No key findings returned.</p>}<ol>{insights.findings.map((f,i)=><li className="analysis-item" key={i}><div className="flex flex-wrap items-center gap-2"><span className="muted text-xs">{i+1}.</span><h3>{f.title}</h3><Badge tone={f.severity}>{f.severity}</Badge>{f.column&&<span className="cell-mono muted">{f.column}</span>}</div><p>{f.description}</p></li>)}</ol><h2 className="mt-7">Suggested Checks</h2><p className="muted text-xs mt-1">Recommendations only. Nothing is applied or saved automatically.</p>{!insights.suggested_checks.length&&<p className="muted mt-2">No additional checks suggested.</p>}{insights.suggested_checks.map((c,i)=><div className="analysis-item" key={i}><div className="flex flex-wrap items-center gap-2"><h3>{ruleLabel(c.rule)}</h3><span className="cell-mono muted">{c.column}</span><Badge tone="info">Suggestion only</Badge></div>{c.parameters.value!==null&&<p>Value: {c.parameters.value}</p>}{c.parameters.values!==null&&<p>Allowed values: {c.parameters.values.map(String).join(', ')}</p>}<p>{c.reason}</p></div>)}</>}
 </>}</Card>
}
